"""Regression tests for the bounded Proffer XML signature probe.

Generated by: Codex (D02 Sources/Catalog) | Date: 2026-09-23 | Rev: 1 |
Platform: Codex / win32
"""

from __future__ import annotations

from pathlib import Path

import pytest

from server.contracts.ingest import IngestLane, IngestRequest
from server.contracts.records import NormalizedRecord
from server.proffer import service


class _ReadGuard:
    def __init__(self, stream, reads: list[int]) -> None:
        self.stream = stream
        self.reads = reads

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, traceback):
        return self.stream.__exit__(exc_type, exc, traceback)

    def read(self, size: int = -1) -> bytes:
        self.reads.append(size)
        assert 0 <= size <= 4096, "XML probe attempted an unbounded read"
        return self.stream.read(size)


@pytest.mark.parametrize(
    ("prefix", "expected_format"),
    [
        (b"<?xml version='1.0'?><smses count='0'></smses>", "smsbackuprestore-xml"),
        (b"<?xml version='1.0'?><mms address='x'/>", "smsbackuprestore-xml"),
        (b"<?xml version='1.0'?><other/>", None),
        (
            b'<!DOCTYPE root [<!ENTITY x SYSTEM "https://invalid.example/x">]><root>&x;</root>',
            None,
        ),
    ],
)
def test_xml_probe_reads_only_prefix_and_keeps_routing(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, prefix: bytes, expected_format: str | None
) -> None:
    source = tmp_path / "large.xml"
    with source.open("wb") as stream:
        stream.write(prefix)
        stream.truncate(64 * 1024 * 1024)

    original_open = Path.open
    reads: list[int] = []

    def guarded_open(path: Path, *args, **kwargs):
        stream = original_open(path, *args, **kwargs)
        return _ReadGuard(stream, reads) if path == source else stream

    def forbidden_read_bytes(path: Path) -> bytes:
        if path == source:
            pytest.fail("XML probe read the whole source")
        return original_read_bytes(path)

    original_read_bytes = Path.read_bytes
    monkeypatch.setattr(Path, "open", guarded_open)
    monkeypatch.setattr(Path, "read_bytes", forbidden_read_bytes)

    observed: list[tuple[str, str | None]] = []

    def fake_parse(path, source_meta, *, engine, format):
        observed.append((engine, format))
        return [NormalizedRecord(source="fixture", content="message")], "fixture", []

    monkeypatch.setattr("server.analysis.chat_parse.parse_chat_export", fake_parse)
    request = IngestRequest(staged_path=str(source), lane=IngestLane.context)
    records, _parser_id, engine, _attempts = service._parse(source, request)

    assert records[0].content == "message"
    assert engine == "go"
    assert observed == [("go", expected_format)]
    assert reads == [4096]


def test_xml_signature_beyond_probe_window_does_not_change_hint(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    source = tmp_path / "late.xml"
    source.write_bytes(b" " * 4096 + b"<smses count='0'></smses>")
    observed: list[str | None] = []

    def fake_parse(path, source_meta, *, engine, format):
        observed.append(format)
        return [NormalizedRecord(source="fixture", content="message")], "fixture", []

    monkeypatch.setattr("server.analysis.chat_parse.parse_chat_export", fake_parse)
    service._parse(source, IngestRequest(staged_path=str(source), lane=IngestLane.context))

    assert observed == [None]


@pytest.mark.parametrize(
    ("filename", "payload", "expected_format", "expected_reads"),
    [
        ("empty.xml", b"", None, [4096]),
        ("truncated.xml", b"<?xml version='1.0'?><sms", None, [4096]),
        ("small.xml", b"<smses count='0'/>", "smsbackuprestore-xml", [4096]),
        ("generic.xml", b"<?xml version='1.0'?><document/>", None, [4096]),
        ("not-xml.txt", b"<smses count='0'/>", None, []),
    ],
)
def test_xml_probe_short_and_non_xml_inputs(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    filename: str,
    payload: bytes,
    expected_format: str | None,
    expected_reads: list[int],
) -> None:
    source = tmp_path / filename
    source.write_bytes(payload)
    original_open = Path.open
    reads: list[int] = []

    def guarded_open(path: Path, *args, **kwargs):
        if path == source:
            if not expected_reads:
                pytest.fail("non-XML source was opened by the XML probe")
            return _ReadGuard(original_open(path, *args, **kwargs), reads)
        return original_open(path, *args, **kwargs)

    monkeypatch.setattr(Path, "open", guarded_open)
    observed: list[str | None] = []

    def fake_parse(path, source_meta, *, engine, format):
        observed.append(format)
        return [NormalizedRecord(source="fixture", content="message")], "fixture", []

    monkeypatch.setattr("server.analysis.chat_parse.parse_chat_export", fake_parse)
    service._parse(source, IngestRequest(staged_path=str(source), lane=IngestLane.context))

    assert observed == [expected_format]
    assert reads == expected_reads
