
import { StagedVideo, CaseData, TimelineEvent, Entity, ForensicAnalysis } from '../types';

export const transformToDbSchema = (videos: StagedVideo[], speakerMap: Record<string, string>, existingData: CaseData | null): CaseData => {
    const newCaseData: CaseData = existingData ? JSON.parse(JSON.stringify(existingData)) : {
        events: [],
        entities: [],
        entityRelationships: [],
        globalNotes: []
    };

    // Only operate on videos that have been explicitly verified by the user
    const verifiedVideos = videos.filter(v => v.status === 'Verified' && v.report);

    for (const video of verifiedVideos) {
        if (!video.report) continue;
        
        // Avoid adding duplicate events by checking the unique video ID
        if (newCaseData.events.some(e => e.id === video.id)) continue;

        const report = video.report;
        const allInvolvedParties = new Set<string>();
        
        const witnesses = report.transcript ? [...new Set(report.transcript.map(t => speakerMap[t.speaker] || t.speaker))] : [];
        witnesses.forEach(w => allInvolvedParties.add(w));

        const involvedEntityNames = report.entities.map(e => e.name);
        involvedEntityNames.forEach(e => allInvolvedParties.add(e));

        const event: TimelineEvent = {
            id: video.id,
            date: new Date().toISOString(),
            description: video.description, // Use user-verified description
            category: video.category,
            location: video.location,
            witnesses: witnesses,
            involvedEntities: Array.from(allInvolvedParties),
            isSignificant: video.isSignificant,
            manipulationPattern: video.manipulationPattern,
            evidenceStrength: video.evidenceStrength,
            aiAnalysis: JSON.stringify(report), // Store the raw AI report for reference
            forensicAnalysis: video.forensicAnalysis, // Add the advanced analysis object
        };
        newCaseData.events.push(event);

        // Add/update entities from the report
        allInvolvedParties.forEach(name => {
            if (!newCaseData.entities.some(e => e.name === name)) {
                const entityReport = report.entities.find(re => re.name === name);
                newCaseData.entities.push({
                    id: name.replace(/\s+/g, '_').toLowerCase() + `_${Date.now()}`,
                    name: name,
                    type: 'person',
                    relationship: 'Unknown',
                    impactOnCase: 'medium',
                    notes: entityReport?.description || 'Observed in video analysis.',
                });
            }
        });
    }

    return newCaseData;
};


// --- Graph Database (Cypher) Transformation ---

export const generateCypherScript = (videos: StagedVideo[], speakerMap: Record<string, string>): string => {
    let script = `// Cypher script generated by Forensic Video Analyzer\n// ${new Date().toISOString()}\n\n`;

    const allEntities = new Map<string, Entity>();

    // Use the same transformation logic to get the final, clean data
    const caseData = transformToDbSchema(videos, speakerMap, null);
    
    caseData.entities.forEach(entity => {
        if (!allEntities.has(entity.name)) {
            allEntities.set(entity.name, entity);
        }
    });

    script += "// --- 1. Create Entity Nodes ---\n";
    allEntities.forEach(entity => {
        script += `MERGE (e:Entity {id: '${entity.id}'}) ON CREATE SET e.name = '${entity.name.replace(/'/g, "\\'")}', e.type = '${entity.type}', e.notes = '${entity.notes.replace(/'/g, "\\'")}';\n`;
    });
    script += "\n";

    script += "// --- 2. Create Event Nodes and Relationships ---\n";
    caseData.events.forEach((event, index) => {
        script += `// -- Event from Video: ${event.description.split('.')[0]}\n`;
        script += `MERGE (ev:Event {id: '${event.id}'}) ON CREATE SET ev.date = '${event.date}', ev.category = '${event.category}', ev.description = '${event.description.replace(/'/g, "\\'")}';\n`;

        // Add forensic analysis properties to the Event node
        if (event.forensicAnalysis) {
            script += `SET ev.sentiment = '${event.forensicAnalysis.sentiment}', ev.deceptionScore = ${event.forensicAnalysis.deceptionScore};\n`;
        }

        // Link involved entities
        event.involvedEntities.forEach(entityName => {
            const entity = allEntities.get(entityName);
            if (entity) {
                script += `MATCH (e:Entity {id: '${entity.id}'}), (ev:Event {id: '${event.id}'}) MERGE (e)-[:INVOLVED_IN]->(ev);\n`;
            }
        });

        // Link witnesses
        event.witnesses.forEach(witnessName => {
            const entity = allEntities.get(witnessName);
            if (entity) {
                script += `MATCH (e:Entity {id: '${entity.id}'}), (ev:Event {id: '${event.id}'}) MERGE (e)-[:WITNESSED]->(ev);\n`;
            }
        });
        script += "\n";
    });

    return script;
};
