#!/usr/bin/env bash
# =============================================================================
# Kasm Workspaces CE — one-time host install on ovh-files (portal item P-1, step 2).
# Owner order 2026-09-26 23:42-23:48 (2026-09-27-TODO.md #1): "The devbox should be the Kasm workspace".
#
# RECORDED EXCEPTION to "containers are declared in Coolify": Kasm's own containers (kasm_proxy,
# kasm_api, kasm_manager, kasm_agent, kasm_db, kasm_guac, kasm_rdp_gateway, ...) are created and
# managed by Kasm's installer under /opt/kasm, not by Coolify. This tracked script is the only way
# they are created, and it is run once, as recorded host prep (log: Consignatio docs/URGENT-TODO.md).
#
# Pins: release 1.19.0 "initial build" bundle, sha256 below = the value Kasm publishes beside the
# tarball on S3 (kasm_release_1.19.0.tar.gz.sha256sum, checked 2026-10-02). The Kasm docs FAQ lists a
# different hash (7b801cb0…) that matches neither the 1.19.0 nor the 1.19.0-latest tarball today.
# Service images are pulled online from Docker Hub by the installer (no -W: no default workspace images;
# our own workspaces are registered afterwards, see README.md).
#
# Flags: --accept-eula, --proxy-port 8443 (Coolify's Traefik owns 443 on this host), --admin-password /
# --user-password generated here. No --swap-size: the host already has an 8 GB swapfile.
# Exposure: Docker publishes 8443 and 3389 on all interfaces, but the host's DOCKER-USER chain drops
# everything arriving on the public interface ens3 (checked 2026-10-02), so both are tailnet/private only.
#
# Run (from the desktop; nothing runs locally):
#   ssh -i ~/.ssh/ovh root@100.91.190.107 'bash -s' < deploy/kasm/install_kasm.sh
# Credentials: /data/probata/secrets/kasm/kasm.env (0600, root). Never printed. Copy to the desktop's
# ~/.secrets/kasm.env with scp, not by echoing.
#
# Byline: Claude Code · Opus 5.5 · 2026-10-02
# =============================================================================
set -euo pipefail

KASM_VERSION=1.19.0
KASM_TARBALL="kasm_release_${KASM_VERSION}.tar.gz"
KASM_SHA256=8caaa12d97fdd0c20b39b10f50ebe2e0da1951b22a427c60a06491a9ed515d6d
KASM_URL_BASE=https://kasm-static-content.s3.amazonaws.com
PROXY_PORT=8443
SECRETS=/data/probata/secrets/kasm
STAGE="/data/probata/kasm-installer/${KASM_VERSION}"

[[ "$(id -u)" == 0 ]] || { echo "run as root"; exit 2; }

# --- pre-flight: install once, ports free, swap present ---
if [[ -d /opt/kasm ]]; then
  echo "STOP: /opt/kasm exists — Kasm is already installed. This script installs once; upgrades follow Kasm's upgrade guide."
  exit 3
fi
for p in 3389 "${PROXY_PORT}"; do
  if ss -Hltn "sport = :${p}" | grep -q .; then
    echo "STOP: port ${p} is in use on this host:"; ss -Hltnp "sport = :${p}"
    exit 4
  fi
done
if [[ -z "$(swapon --show --noheadings)" ]]; then
  echo "STOP: no swap on this host; re-run with the installer's --swap-size after an owner decision"
  exit 5
fi

# --- download + verify against the pinned hash ---
install -d -m 0755 "${STAGE}"
cd "${STAGE}"
[[ -f "${KASM_TARBALL}" ]] || curl -fsSLO "${KASM_URL_BASE}/${KASM_TARBALL}"
echo "${KASM_SHA256}  ${KASM_TARBALL}" | sha256sum -c -
[[ -d kasm_release ]] && mv kasm_release "kasm_release.prev-$(date -u +%Y%m%dT%H%M%SZ)"   # never delete; set aside
tar -xf "${KASM_TARBALL}"

# --- credentials (generated once, kept on the host, never printed) ---
umask 077
install -d -m 0700 "${SECRETS}"
if [[ ! -f "${SECRETS}/kasm.env" ]]; then
  gen() { openssl rand -base64 36 | tr -d '/+=\n' | cut -c1-28; }
  {
    echo "# Kasm Workspaces CE on ovh-files — generated by deploy/kasm/install_kasm.sh $(date -u +%FT%TZ)"
    echo "KASM_URL=https://kasm.tilapia-skilift.ts.net"
    echo "KASM_DIRECT_URL=https://100.91.190.107:${PROXY_PORT}"
    echo "KASM_ADMIN_USER=admin@kasm.local"
    echo "KASM_ADMIN_PASSWORD=$(gen)"
    echo "KASM_USER_USER=user@kasm.local"
    echo "KASM_USER_PASSWORD=$(gen)"
  } > "${SECRETS}/kasm.env"
fi
val() { sed -nE "s/^\s*$1\s*=\s*(.*)\s*$/\1/p" "${SECRETS}/kasm.env" | tail -1; }
ADMIN_PW="$(val KASM_ADMIN_PASSWORD)"
USER_PW="$(val KASM_USER_PASSWORD)"
[[ -n "${ADMIN_PW}" && -n "${USER_PW}" ]] || { echo "STOP: kasm.env lacks passwords"; exit 6; }

# --- install (its log contains the credentials, so it stays in the secrets folder) ---
LOG="${SECRETS}/install-$(date -u +%Y%m%dT%H%M%SZ).log"
set +e
bash kasm_release/install.sh --accept-eula --proxy-port "${PROXY_PORT}" \
  --admin-password "${ADMIN_PW}" --user-password "${USER_PW}" > "${LOG}" 2>&1
rc=$?
set -e
echo "install.sh exit ${rc}; full log (contains credentials, 0600): ${LOG}"
grep -iE "installation complete|error|failed" "${LOG}" | grep -viE "password|token" | tail -15 || true
docker ps --filter name=kasm_ --format '{{.Names}}\t{{.Status}}'
exit "${rc}"
