// Byline: Claude Code · Sonnet 5 · 2026-09-08 — added the content-store.ts dist entry and
// Updated by: OpenAI Codex · GPT-5 · 2026-09-12 — shared host-aware theme and safe connection transform.
// localExternalsPlugin() (see the commonBuildOptions comment below) so that every dist/*.js
// entry point shares ONE runtime copy of store.ts's module-level store cache.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const rawBundle = readFileSync(require.resolve("@modelcontextprotocol/ext-apps/app-with-deps"), "utf8");
const browserBundle = rawBundle.replace(/export\{([^}]+)\};?\s*$/, (_, body) =>
  "globalThis.ExtApps={" + body.split(",").map((pair) => {
    const [local, exported] = pair.split(" as ").map((value) => value.trim());
    return `${exported ?? local}:${local}`;
  }).join(",") + "};"
);
const workbenchTheme = readFileSync(join(here, "widgets", "workbench-theme.css"), "utf8");
const workbenchHost = readFileSync(join(here, "widgets", "workbench-host.js"), "utf8");

function stripLegacyDarkMediaQueries(source) {
  const marker = "@media(prefers-color-scheme:dark)";
  let result = source;
  while (result.includes(marker)) {
    const start = result.indexOf(marker);
    const open = result.indexOf("{", start);
    let depth = 0;
    let end = open;
    for (; end < result.length; end += 1) {
      if (result[end] === "{") depth += 1;
      if (result[end] === "}") depth -= 1;
      if (depth === 0) break;
    }
    if (open < 0 || end >= result.length) throw new Error("Malformed legacy dark-mode media query");
    result = result.slice(0, start) + result.slice(end + 1);
  }
  return result;
}

const names = ["dashboard", "route", "deadline", "packet", "checklist", "sources", "search", "chronology"];
const widgets = Object.fromEntries(names.map((name) => {
  const source = stripLegacyDarkMediaQueries(readFileSync(join(here, "widgets", `${name}.html`), "utf8"));
  const connectCalls = source.match(/await app\.connect\(\)/g) ?? [];
  if (connectCalls.length !== 1) throw new Error(`${name} must contain exactly one app.connect() call`);
  const connectedSource = source.replace("await app.connect()", "await connectWorkbenchApp(app)");
  const html = connectedSource
    .replace("color-scheme:light dark", "color-scheme:dark")
    .replaceAll("CanvasText", "var(--fc-text)")
    .replaceAll("Canvas", "var(--fc-surface)")
    .replace("<script type=\"module\">", () => `<style>\n${workbenchTheme}\n</style><script type=\"module\">`)
    .replace("/*__EXT_APPS_BUNDLE__*/", () => `${browserBundle}\n${workbenchHost}\n`);
  return [name, html];
}));

mkdirSync(join(here, "src"), { recursive: true });
writeFileSync(join(here, "src", "generated-widgets.ts"),
  `// Generated by build.mjs.\nexport const widgets = ${JSON.stringify(widgets)} as const;\n`, "utf8");
mkdirSync(join(here, "dist"), { recursive: true });
const surrealExternal = ["surrealdb", "@surrealdb/node"];
// Every OUR-OWN local module that (transitively) touches store.ts's
// module-level getStore() cache MUST be a real runtime import to the ONE
// shared dist file, never re-bundled/inlined per entry point. Each
// `await build()` below (bundle: true) otherwise inlines a local import
// (e.g. "./store.js") as its own private copy of that module's code —
// meaning its own private `cachedStore`. That is harmless for a remote ws://
// store (every copy just opens its own client connection to the same remote
// server) but actively wrong for the embedded engines: two independent opens
// of the same rocksdb:// PATH from one process can lock-conflict, and two
// independent opens of "mem://" are two DIFFERENT, mutually invisible
// in-memory databases — exactly the failure mode content-store.ts introduces
// the moment core.ts/court-language.ts/survival-guide.ts gained a
// (transitive) store.ts dependency.
//
// A plain string in esbuild's `external` array matches by import-specifier
// TEXT ONLY, with no awareness of which file wrote the import — and zod v4's
// own internal module tree contains files that ALSO import a relative
// "./core.js" (verified live: node_modules/zod/v4/core/errors.js). Naively
// externalizing "./core.js" broke that too, pointing zod's own internal
// import at our dist/core.js. This plugin instead externalizes a match ONLY
// when the importing file is one of OUR OWN src/*.ts files (never something
// under node_modules), so the two "./core.js"s never collide.
// Claude Code · Sonnet 5 · 2026-09-08.
const localModuleNames = ["store", "store-tools", "core", "court-language", "survival-guide", "content-store"];
function localExternalsPlugin() {
  const filter = new RegExp(`^\\./(${localModuleNames.join("|")})\\.js$`);
  return {
    name: "local-externals",
    setup(pluginBuild) {
      pluginBuild.onResolve({ filter }, (args) => {
        if (args.importer.includes(`${sep}node_modules${sep}`)) return null; // let esbuild resolve a third-party module of the same relative name normally
        return { path: args.path, external: true };
      });
    },
  };
}
const commonBuildOptions = { external: surrealExternal, plugins: [localExternalsPlugin()] };

await build({
  entryPoints: [join(here, "src", "server.ts")],
  ...commonBuildOptions,
  outfile: join(here, "dist", "server.js"),
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  sourcemap: false,
  banner: { js: "// Byline: OpenAI Codex / GPT-5.6, 2026-08-13" }
});
await build({
  entryPoints: [join(here, "src", "core.ts")],
  outfile: join(here, "dist", "core.js"),
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  sourcemap: false,
  ...commonBuildOptions,
  banner: { js: "// Byline: OpenAI Codex / GPT-5.6, 2026-08-13" }
});
// Byline: Claude Code · Fable 5.1 · 2026-09-07 — separate dist entries for the
// two new tool engines so tests/tools_new.test.mjs can unit-test them directly,
// the same way core.test.mjs unit-tests dist/core.js.
await build({
  entryPoints: [join(here, "src", "survival-guide.ts")],
  outfile: join(here, "dist", "survival-guide.js"),
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  sourcemap: false,
  ...commonBuildOptions,
  banner: { js: "// Byline: Claude Code · Fable 5.1 · 2026-09-07" }
});
await build({
  entryPoints: [join(here, "src", "court-language.ts")],
  outfile: join(here, "dist", "court-language.js"),
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  sourcemap: false,
  ...commonBuildOptions,
  banner: { js: "// Byline: Claude Code · Fable 5.1 · 2026-09-07" }
});
// Byline: Claude Code · Sonnet 5 · 2026-09-08 — content-store.ts's own dist entry, so
// tests/content_store.test.mjs can unit-test getReference()/getSources() directly,
// and so every OTHER dist file that reads content (core.js, court-language.js,
// survival-guide.js) shares this exact ONE compiled copy (see localExternal above).
await build({
  entryPoints: [join(here, "src", "content-store.ts")],
  outfile: join(here, "dist", "content-store.js"),
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  sourcemap: false,
  ...commonBuildOptions,
  banner: { js: "// Byline: Claude Code · Sonnet 5 · 2026-09-08" }
});
// Byline: Claude Code · Fable 5.1 · 2026-09-07 — case-store dist entries. Both
// `surrealdb` and `@surrealdb/node` are marked external: @surrealdb/node ships
// native .node binaries that esbuild cannot bundle (bundling them was tried
// first and fails), so mcp-app must ship real node_modules for these two
// packages (`npm ci --omit=dev` after install — see README-store.md).
// (moved above the server build — server.js must not inline the native engine; Claude Code · Fable 5.1 · 2026-09-07)
await build({
  entryPoints: [join(here, "src", "store.ts")],
  outfile: join(here, "dist", "store.js"),
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  sourcemap: false,
  ...commonBuildOptions,
  banner: { js: "// Byline: Claude Code · Fable 5.1 · 2026-09-07" }
});
await build({
  entryPoints: [join(here, "src", "store-tools.ts")],
  outfile: join(here, "dist", "store-tools.js"),
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  sourcemap: false,
  ...commonBuildOptions,
  banner: { js: "// Byline: Claude Code · Fable 5.1 · 2026-09-07" }
});
