"""Synthetic image search checks for literal OCR and visual channel isolation.

Generated by: Codex (D03 Case Bible search) | Date: 2026-09-23 | Rev: 1 |
Platform: Codex / win32
"""

import json

import httpx
import pytest

from casebible_index.image_search import WeaviateImageSearcher, _literal_span


def _row(object_id, source_path, ocr_text, *, score=1.0, distance=0.2):
    return {
        "source_id": "synthetic-vault",
        "source_path": source_path,
        "filename": source_path.rsplit("/", 1)[-1],
        "content_sha256": "a" * 64,
        "original_time": "",
        "original_time_source": "",
        "original_time_confidence": "",
        "original_time_conflict": False,
        "device": "",
        "software": "",
        "gps": "",
        "is_screenshot": True,
        "ocr_text": ocr_text,
        "_additional": {"id": object_id, "score": score, "distance": distance},
    }


def _transport(bm25_rows, single_rows=(), maxsim_rows=()):
    def serve(request):
        query = json.loads(request.content)["query"]
        if "bm25:" in query:
            rows = bm25_rows
        elif 'targetVectors: ["image_single"]' in query:
            rows = single_rows
        elif 'targetVectors: ["image_maxsim"]' in query:
            rows = maxsim_rows
        else:
            raise AssertionError("Unexpected Weaviate operator")
        return httpx.Response(200, json={"data": {"Get": {"IntakeSynthetic": rows}}})

    return httpx.MockTransport(serve)


def test_literal_span_preserves_original_offsets_with_unicode_and_whitespace():
    retained = "Before\tCAFÉ\nappointment after"
    span = _literal_span(retained, "cafe\u0301 appointment")
    assert span is not None
    assert retained[slice(*span)] == "CAFÉ\nappointment"
    assert _literal_span("the meeting is tomorrow", "meeting today") is None


@pytest.mark.asyncio
async def test_keyword_requires_verified_ocr_and_keeps_each_occurrence():
    text = "Reminder: Café\nappointment at noon"
    rows = [
        _row("occurrence-a", "copies/a/screenshot.png", text),
        _row("occurrence-b", "copies/b/screenshot.png", text),
        _row("bm25-false-positive", "copies/c/screenshot.png", "Appointment is next week"),
    ]
    hits = await WeaviateImageSearcher("https://weaviate.example", "IntakeSynthetic").search(
        "CAFÉ appointment", limit=10, mode="keyword", embedders=None,
        transport=_transport(rows),
    )
    assert {hit.object_id for hit in hits} == {"occurrence-a", "occurrence-b"}
    assert {hit.source_path for hit in hits} == {
        "copies/a/screenshot.png", "copies/b/screenshot.png",
    }
    assert {hit.content_sha256 for hit in hits} == {"a" * 64}
    for hit in hits:
        assert hit.channel == hit.matched_by == "ocr_literal"
        assert hit.score_basis == "weaviate_bm25"
        assert text[hit.ocr_span_start:hit.ocr_span_end] == "Café\nappointment"
        assert hit.region_status == "not_recorded"
        assert "region" not in hit.model_dump()


@pytest.mark.asyncio
async def test_hybrid_semantic_candidates_do_not_become_literal_ocr():
    class FakeEmbedders:
        async def embed_query(self, query):
            assert query == "signed document"
            return [0.5, 0.5], [[0.3, 0.7]]

    bm25_false = _row("bm25-false", "a.png", "The document was discussed")
    visual_only = _row("visual-only", "b.png", "No matching phrase")
    vector_with_text = _row("vector-text", "c.png", "signed document")
    hits = await WeaviateImageSearcher("https://weaviate.example", "IntakeSynthetic").search(
        "signed document", limit=10, mode="hybrid", embedders=FakeEmbedders(),
        transport=_transport([bm25_false], [visual_only, vector_with_text], [visual_only]),
    )
    assert {hit.object_id for hit in hits} == {"visual-only", "vector-text"}
    assert next(hit for hit in hits if hit.object_id == "visual-only").matched_by == "maxsim"
    for hit in hits:
        assert hit.channel == "visual_similarity"
        assert hit.ocr_span_start is None and hit.ocr_span_end is None
        assert hit.ocr_excerpt == ""
        assert hit.region_status == "not_recorded"


@pytest.mark.asyncio
async def test_long_verified_phrase_is_present_in_excerpt():
    phrase = "long phrase " * 35
    hit = _row("long-phrase", "long.png", "prefix " + phrase + " suffix")
    results = await WeaviateImageSearcher("https://weaviate.example", "IntakeSynthetic").search(
        phrase, limit=1, mode="keyword", embedders=None, transport=_transport([hit]),
    )
    assert len(results) == 1
    assert phrase in results[0].ocr_excerpt
