// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Browse() {
  return window['go']['main']['App']['Browse']();
}

export function BrowseForExport(arg1) {
  return window['go']['main']['App']['BrowseForExport'](arg1);
}

export function DetectCloudDrives() {
  return window['go']['main']['App']['DetectCloudDrives']();
}

export function ExportResults(arg1, arg2) {
  return window['go']['main']['App']['ExportResults'](arg1, arg2);
}

export function ExportSettings(arg1) {
  return window['go']['main']['App']['ExportSettings'](arg1);
}

export function GetCloudDrives() {
  return window['go']['main']['App']['GetCloudDrives']();
}

export function GetCurrentProgress() {
  return window['go']['main']['App']['GetCurrentProgress']();
}

export function GetCurrentTime() {
  return window['go']['main']['App']['GetCurrentTime']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetScanStatus() {
  return window['go']['main']['App']['GetScanStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportSettings(arg1) {
  return window['go']['main']['App']['ImportSettings'](arg1);
}

export function LoadChildrenLazy(arg1, arg2) {
  return window['go']['main']['App']['LoadChildrenLazy'](arg1, arg2);
}

export function PauseScan() {
  return window['go']['main']['App']['PauseScan']();
}

export function ResumeScan() {
  return window['go']['main']['App']['ResumeScan']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartScan(arg1) {
  return window['go']['main']['App']['StartScan'](arg1);
}

export function StopScan() {
  return window['go']['main']['App']['StopScan']();
}

export function SubscribeScanProgress() {
  return window['go']['main']['App']['SubscribeScanProgress']();
}
