"""
mirror_docs.py — D-156 docs-tree mirror regeneration tool.

Byline: Claude Code · Sonnet 5 · 2026-09-09

Ruling: docs/DECISION_LOG.md D-156. Design: docs/design/2026-09-09-docstore-memory-plugin-design.md
§7 item 2 ("moving files by hand breaks every relative link again" — fixed by generating the
mirror from a mapping table, never by hand) and §8 step 5 ("regenerate the seven-folder mirror
from the store with frontmatter; dead-link count before and after ... must not rise; INDEX.md
is generated").

After ingest, the on-disk `docs/` tree is regenerated as seven folders — `docs/blueprint`,
`docs/infrastructure`, `docs/decision`, `docs/todo`, `docs/handoff`, `docs/review`,
`docs/reference` — driven by a per-file mapping CSV (source_path, doc_type, domains, status,
supersedes_path, title, bytes, sha256, mirror_path, notes). Every moved document gets YAML
frontmatter (type/domains/status/supersedes/source_path), relative markdown links are rewritten
to follow their moved targets, `docs/INDEX.md` becomes a generated view grouped by type then
domain with a status column, and files move via `git mv` so history follows. The dead-link count
(computed by the same method as the 2026-09-09 "walk G" / in-place-fixes gate: scan
`docs/**/*.md` excluding `docs/private/`, extract markdown link targets, drop http(s)/mailto/
anchor-only/placeholder/code-span matches, treat a leading-`/` absolute-style target as always
dead, test the remainder's existence relative to the linking file's directory) must not rise
after `--apply`.

Modes
-----
--plan (default)   Read-only. Verifies the mapping CSV, computes the full move list and every
                   link rewrite, computes dead-links-before and projected dead-links-after,
                   writes `mirror-plan.json` + `mirror-plan.md` to the job's out/ dir. Makes NO
                   filesystem or git changes.
--index-only       Read-only. Regenerates `docs/INDEX.md`'s content from the CSV alone (no
                   moves) and writes the PREVIEW to scratch, never to the repo.
--apply            Executes the plan: `git mv` per file, frontmatter injection, link rewrites,
                   INDEX.md generation; re-checks the dead-link count and refuses (non-zero
                   exit, offending links printed, no rollback attempted — the operator reverts
                   via git) if it rose. NEVER invoked by the build/dry-run job that wrote this
                   file — see the job's report for the exact command to run later.

Usage
-----
    "C:/Users/matts/.local/bin/python3.exe" scripts/docstore/mirror_docs.py --plan
    "C:/Users/matts/.local/bin/python3.exe" scripts/docstore/mirror_docs.py --index-only
    "C:/Users/matts/.local/bin/python3.exe" scripts/docstore/mirror_docs.py --apply   # NOT run here

All paths below default to this job's fixed locations but are overridable via flags so the tool
is reusable for a future ingest run.
"""

from __future__ import annotations

import argparse
import csv
import datetime
import json
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

# ---------------------------------------------------------------------------
# Defaults (this job's fixed locations)
# ---------------------------------------------------------------------------

# Derived from this file's location, never hard-coded: the checkout was moved
# (the-platform-workspace -> Propria/Probata) on 2026-09-09 and an absolute
# literal here silently made every mapping source "missing" (503/503), which
# reads as data loss rather than a stale path. scripts/docstore/ -> parents[2].
REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS_ROOT = REPO_ROOT / "docs"
DEFAULT_MAPPING_CSV = Path(
    r"C:/Users/matts/.claude/jobs/68afe1c5/tmp/out/docs-ingest-mapping.csv"
)
DEFAULT_OUT_DIR = Path(r"C:/Users/matts/.claude/jobs/68afe1c5/tmp/out")
DEFAULT_SCRATCH_DIR = Path(r"C:/Users/matts/.claude/jobs/68afe1c5/tmp")

RULED_TYPES = [
    "blueprint", "infrastructure", "decision", "todo", "handoff", "review", "reference",
]
RULED_STATUS = ["active", "proposed", "unverified", "superseded", "retracted"]

MODEL_BYLINE = "Sonnet 5"  # for the frontmatter mirror-regenerated byline line

TYPE_ORDER = {t: i for i, t in enumerate(RULED_TYPES)}
STATUS_ORDER = {s: i for i, s in enumerate(RULED_STATUS)}

# ---------------------------------------------------------------------------
# Long-path safety (MAX_PATH ~260 on Windows). Only engaged when a resolved
# absolute path is long enough to risk it; reported when it triggers.
# ---------------------------------------------------------------------------

_LONGPATH_USED: set[str] = set()


def winlong(p: Path) -> str:
    s = str(p.resolve()) if not str(p).startswith("\\\\?\\") else str(p)
    if os.name == "nt" and len(s) >= 240 and not s.startswith("\\\\?\\"):
        _LONGPATH_USED.add(s)
        return "\\\\?\\" + s
    return s


def read_text(p: Path) -> str:
    with open(winlong(p), "r", encoding="utf-8", errors="replace", newline="") as f:
        return f.read()


def file_exists(p: Path) -> bool:
    try:
        return os.path.isfile(winlong(p))
    except OSError:
        return False


# ---------------------------------------------------------------------------
# Mapping CSV
# ---------------------------------------------------------------------------


@dataclass
class MapRow:
    source_path: str  # "docs/..." posix, relative to REPO_ROOT
    doc_type: str
    domains: list[str]
    status: str
    supersedes_path: str
    title: str
    nbytes: int
    sha256: str
    mirror_path: str
    notes: str

    @property
    def moves(self) -> bool:
        return self.source_path != self.mirror_path


def load_mapping(csv_path: Path) -> list[MapRow]:
    rows: list[MapRow] = []
    with open(csv_path, encoding="utf-8", newline="") as f:
        for r in csv.DictReader(f):
            rows.append(
                MapRow(
                    source_path=r["source_path"].replace("\\", "/"),
                    doc_type=r["doc_type"].strip(),
                    domains=[d for d in r["domains"].split("|") if d],
                    status=r["status"].strip(),
                    supersedes_path=(r["supersedes_path"] or "").replace("\\", "/"),
                    title=r["title"],
                    nbytes=int(r["bytes"]) if r["bytes"] else 0,
                    sha256=r["sha256"],
                    mirror_path=r["mirror_path"].replace("\\", "/"),
                    notes=r.get("notes", ""),
                )
            )
    return rows


def verify_mapping(rows: list[MapRow]) -> dict:
    """Every source exists; every mirror_path unique. Returns a report dict;
    does not raise — the caller decides whether missing sources are fatal."""
    missing_sources = []
    for r in rows:
        if not file_exists(REPO_ROOT / r.source_path):
            missing_sources.append(r.source_path)

    seen: dict[str, list[str]] = {}
    for r in rows:
        seen.setdefault(r.mirror_path, []).append(r.source_path)
    dupes = {m: srcs for m, srcs in seen.items() if len(srcs) > 1}

    bad_types = [r.source_path for r in rows if r.doc_type not in RULED_TYPES]
    bad_status = [r.source_path for r in rows if r.status not in RULED_STATUS]

    return {
        "missing_sources": missing_sources,
        "duplicate_mirror_paths": dupes,
        "bad_types": bad_types,
        "bad_status": bad_status,
    }


# ---------------------------------------------------------------------------
# Link scanning — replicates the 2026-09-09 "walk G" / in-place-fixes-gate
# methodology exactly (see docs/reviews/2026-09-09-inplace-fixes-changelog.md
# "GATE — dead-link count"): scan docs/**/*.md excluding docs/private/,
# extract markdown link targets, drop http(s)/mailto/anchor-only/placeholder/
# code-span matches, a leading-/ target is always dead, else test existence
# relative to the linking file's directory.
# ---------------------------------------------------------------------------

_LINK_RE = re.compile(r"(?<!!)\[([^\]]*)\]\(([^)]+)\)")
_CODE_FENCE_RE = re.compile(r"```.*?```", re.S)
_CODE_SPAN_RE = re.compile(r"`[^`\n]*`")
_SCHEME_RE = re.compile(r"^[a-zA-Z][a-zA-Z0-9+.\-]*://")


def _blank_code(text: str) -> str:
    """Replace fenced/inline code spans with equal-length whitespace so link
    regex offsets still line up with the original text, but code-span
    look-alikes (`[x](y)` inside backticks) never match."""
    text = _CODE_FENCE_RE.sub(lambda m: " " * len(m.group(0)), text)
    text = _CODE_SPAN_RE.sub(lambda m: " " * len(m.group(0)), text)
    return text


def scan_md_files(docs_root: Path) -> list[Path]:
    out = []
    for dirpath, dirnames, filenames in os.walk(docs_root):
        dpath = Path(dirpath)
        rel = dpath.relative_to(docs_root).as_posix() if dpath != docs_root else ""
        if rel == "private" or rel.startswith("private/"):
            dirnames[:] = []
            continue
        for fn in filenames:
            if fn.lower().endswith(".md"):
                out.append(dpath / fn)
    return sorted(out)


@dataclass
class LinkRef:
    label: str
    target: str  # raw target string as written
    path_part: str  # target minus #fragment
    fragment: str  # "" or "#..."
    start: int
    end: int


def extract_links(text: str) -> list[LinkRef]:
    clean = _blank_code(text)
    out = []
    for m in _LINK_RE.finditer(clean):
        label, target = m.group(1), m.group(2).strip()
        if not target:
            continue
        path_part, _, frag = target.partition("#")
        out.append(
            LinkRef(
                label=label, target=target, path_part=path_part,
                fragment=("#" + frag) if frag else "", start=m.start(), end=m.end(),
            )
        )
    return out


def classify_link(link: LinkRef) -> str:
    """Returns one of: 'skip-placeholder', 'skip-anchor', 'skip-scheme',
    'skip-mailto', 'dead-absolute', 'check'."""
    t = link.target.strip()
    if t.upper() == "URL":  # the literal "[Title](URL)" placeholder G discarded
        return "skip-placeholder"
    if not link.path_part:
        return "skip-anchor"  # anchor-only, e.g. "#section"
    if t.startswith("mailto:"):
        return "skip-mailto"
    if _SCHEME_RE.match(t):
        return "skip-scheme"  # http(s):// and any other scheme:// link
    if link.path_part.startswith("/"):
        return "dead-absolute"  # G's rule: leading-/ absolute-style is always dead
    return "check"


def resolve_repo_relpath(from_dir: Path, path_part: str) -> Optional[str]:
    """Resolve a relative link target against from_dir; return the repo-root-
    relative POSIX path string, or None if it resolves outside REPO_ROOT."""
    try:
        raw = path_part
        # tolerate %20 etc. — most links in this repo are plain, but be safe
        from urllib.parse import unquote
        raw = unquote(raw)
        combined = (from_dir / raw).resolve()
        rel = combined.relative_to(REPO_ROOT.resolve())
        return rel.as_posix()
    except (ValueError, OSError):
        return None


# ---------------------------------------------------------------------------
# Dead-link computation (before: live tree today; after: projected post-move)
# ---------------------------------------------------------------------------


@dataclass
class DeadLinkItem:
    file: str
    target: str
    reason: str


def compute_dead_links_before() -> tuple[int, int, list[DeadLinkItem]]:
    """Replicates walk G / the in-place-fixes gate exactly against the LIVE
    tree. Returns (scanned_file_count, checked_link_count, dead_items)."""
    md_files = scan_md_files(DOCS_ROOT)
    checked = 0
    dead: list[DeadLinkItem] = []
    for f in md_files:
        text = read_text(f)
        for link in extract_links(text):
            klass = classify_link(link)
            if klass.startswith("skip"):
                continue
            checked += 1
            if klass == "dead-absolute":
                dead.append(DeadLinkItem(
                    file=f.relative_to(REPO_ROOT).as_posix(),
                    target=link.target,
                    reason="leading-/ absolute-style target (treated as always dead, per walk G)",
                ))
                continue
            resolved = resolve_repo_relpath(f.parent, link.path_part)
            if resolved is None or not file_exists(REPO_ROOT / resolved):
                dead.append(DeadLinkItem(
                    file=f.relative_to(REPO_ROOT).as_posix(),
                    target=link.target,
                    reason=f"resolved target does not exist on disk: {resolved or '(outside repo)'}",
                ))
    return len(md_files), checked, dead


@dataclass
class LinkRewrite:
    file_old: str
    file_new: str
    target_old: str
    target_new: str
    resolved_target_old: str
    resolved_target_new: str


def compute_link_rewrites_and_projected_dead(
    rows: list[MapRow],
) -> tuple[list[LinkRewrite], int, int, list[DeadLinkItem]]:
    """For every managed markdown file (every CSV row whose source_path ends
    in .md — the mapping also carries a handful of non-.md leave-in-place
    rows that never reach here as containers, matching G's docs/**/*.md
    source scope), compute the rewritten link text and the projected dead-
    link set after the move.

    Scope note: the design doc's §8 step 5 / task framing describes rewrites
    as happening "in every moved file." This implementation computes rewrites
    for EVERY row (moved AND the 7 already-at-mirror-path no-op rows) because
    a no-op container can still hold a link to a target that DOES move —
    restricting rewriting to only the container's own move would leave those
    links silently dead. This is a superset of the literal instruction and
    is documented here rather than applied silently.
    """
    move_map = {r.source_path: r.mirror_path for r in rows}
    by_source = {r.source_path: r for r in rows}

    rewrites: list[LinkRewrite] = []
    dead: list[DeadLinkItem] = []
    checked = 0
    scanned = 0

    # Union of every live docs/**/*.md (private excluded) so files outside the
    # CSV (should be none, but verified rather than assumed) are still walked
    # for the "after" projection — their own location does not change.
    live_md = {p.relative_to(REPO_ROOT).as_posix(): p for p in scan_md_files(DOCS_ROOT)}

    for rel_str, abspath in sorted(live_md.items()):
        scanned += 1
        container_row = by_source.get(rel_str)
        container_new_path = container_row.mirror_path if container_row else rel_str
        container_old_dir = abspath.parent
        container_new_dir = REPO_ROOT / container_new_path
        container_new_dir = container_new_dir.parent

        text = read_text(abspath)
        for link in extract_links(text):
            klass = classify_link(link)
            if klass in ("skip-placeholder", "skip-anchor", "skip-scheme", "skip-mailto"):
                continue
            if klass == "dead-absolute":
                checked += 1
                dead.append(DeadLinkItem(
                    file=container_new_path, target=link.target,
                    reason="leading-/ absolute-style target (always dead, per walk G; unaffected by moves)",
                ))
                continue

            checked += 1
            resolved_old = resolve_repo_relpath(container_old_dir, link.path_part)

            if resolved_old is not None and (
                resolved_old.startswith("docs/private/") or resolved_old == "docs/private"
            ):
                # untouched per task spec; existence unaffected by the move
                if not file_exists(REPO_ROOT / resolved_old):
                    dead.append(DeadLinkItem(
                        file=container_new_path, target=link.target,
                        reason=f"docs/private/** target left untouched and does not exist: {resolved_old}",
                    ))
                continue

            if resolved_old is None:
                dead.append(DeadLinkItem(
                    file=container_new_path, target=link.target,
                    reason="link target resolves outside the repository root",
                ))
                continue

            target_row = by_source.get(resolved_old)
            if target_row is not None and target_row.moves:
                # Target is a managed document that is moving — rewrite.
                new_target_abs = REPO_ROOT / target_row.mirror_path
                new_rel = os.path.relpath(new_target_abs, start=container_new_dir)
                new_rel_posix = Path(new_rel).as_posix()
                new_target_str = new_rel_posix + link.fragment
                if container_row is None or not container_row.moves:
                    # container path unchanged, but target moved: still a rewrite
                    pass
                if new_target_str != link.target:
                    rewrites.append(LinkRewrite(
                        file_old=rel_str,
                        file_new=container_new_path,
                        target_old=link.target,
                        target_new=new_target_str,
                        resolved_target_old=resolved_old,
                        resolved_target_new=target_row.mirror_path,
                    ))
                # post-move it exists by construction (source verified to exist)
                continue

            if container_row is not None and container_row.moves and target_row is None:
                # container moves but target is unmanaged (asset/script/etc.)
                # and did not move — link text must still be recomputed even
                # though the target's location is unchanged, because the
                # container's directory changed.
                old_target_abs = REPO_ROOT / resolved_old
                new_rel = os.path.relpath(old_target_abs, start=container_new_dir)
                new_rel_posix = Path(new_rel).as_posix()
                new_target_str = new_rel_posix + link.fragment
                if file_exists(old_target_abs):
                    if new_target_str != link.target:
                        rewrites.append(LinkRewrite(
                            file_old=rel_str, file_new=container_new_path,
                            target_old=link.target, target_new=new_target_str,
                            resolved_target_old=resolved_old, resolved_target_new=resolved_old,
                        ))
                    continue
                else:
                    dead.append(DeadLinkItem(
                        file=container_new_path, target=link.target,
                        reason=f"unmanaged target does not exist on disk: {resolved_old}",
                    ))
                    continue

            # Neither container nor target moves for this link — text stays
            # identical; dead-ness is whatever it is today.
            if not file_exists(REPO_ROOT / resolved_old):
                dead.append(DeadLinkItem(
                    file=container_new_path, target=link.target,
                    reason=f"resolved target does not exist on disk (unaffected by move): {resolved_old}",
                ))

    return rewrites, scanned, checked, dead


# ---------------------------------------------------------------------------
# Frontmatter
# ---------------------------------------------------------------------------

_FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?\n)---\s*\n?", re.S)


def parse_frontmatter(text: str) -> tuple[Optional[dict], str]:
    """Very small YAML-frontmatter parser sufficient for this repo's docs:
    flat `key: value` and `key: [a, b]` / `key: []` lines only (matches what
    D-156's own 2026-09-09 docs actually carry, per the design doc's
    frontmatter merge rule). Returns (fields_dict_or_None, body_after_fm)."""
    m = _FRONTMATTER_RE.match(text)
    if not m:
        return None, text
    block = m.group(1)
    fields: dict = {}
    for line in block.splitlines():
        if not line.strip() or line.strip().startswith("#"):
            continue
        if ":" not in line:
            continue
        k, _, v = line.partition(":")
        k = k.strip()
        v = v.strip()
        if v.startswith("[") and v.endswith("]"):
            inner = v[1:-1].strip()
            fields[k] = [x.strip().strip('"\'') for x in inner.split(",") if x.strip()] if inner else []
        else:
            fields[k] = v.strip('"\'')
    return fields, text[m.end():]


def merge_frontmatter(existing: Optional[dict], row: MapRow) -> dict:
    """Merge rule: never drop existing keys; normalize domain -> domains list;
    fill type/domains/status/supersedes/source_path from the mapping row."""
    merged: dict = dict(existing or {})
    if "domain" in merged and "domains" not in merged:
        dv = merged.pop("domain")
        merged["domains"] = dv if isinstance(dv, list) else [dv]
    elif "domain" in merged and "domains" in merged:
        # keep domains; drop the legacy singular key but preserve its value
        dv = merged.pop("domain")
        existing_list = merged["domains"] if isinstance(merged["domains"], list) else [merged["domains"]]
        addl = dv if isinstance(dv, list) else [dv]
        for d in addl:
            if d not in existing_list:
                existing_list.append(d)
        merged["domains"] = existing_list

    merged.setdefault("type", row.doc_type)
    merged.setdefault("domains", list(row.domains))
    merged.setdefault("status", row.status)
    merged.setdefault("supersedes", row.supersedes_path or "")
    merged.setdefault("source_path", row.source_path)
    # type/status/supersedes/source_path are authoritative from the mapping
    # row (the ingest's own ruling), so overwrite rather than trust a stale
    # ad hoc value already in the file — domains is additive-merged above.
    merged["type"] = row.doc_type
    merged["status"] = row.status
    merged["supersedes"] = row.supersedes_path or ""
    merged["source_path"] = row.source_path
    return merged


def render_frontmatter(fields: dict) -> str:
    lines = ["---"]
    # stable, readable key order
    key_order = ["type", "domains", "status", "supersedes", "source_path"]
    seen = set()
    for k in key_order:
        if k in fields:
            seen.add(k)
            lines.append(_render_kv(k, fields[k]))
    for k in sorted(fields.keys()):
        if k in seen:
            continue
        lines.append(_render_kv(k, fields[k]))
    lines.append("---")
    return "\n".join(lines) + "\n"


def _render_kv(k: str, v) -> str:
    if isinstance(v, list):
        inner = ", ".join(v)
        return f"{k}: [{inner}]"
    return f"{k}: {v}"


def apply_frontmatter_and_byline(text: str, row: MapRow, model_name: str, date_str: str) -> tuple[str, bool, bool]:
    """Returns (new_text, had_existing_fm, byline_added)."""
    existing, body = parse_frontmatter(text)
    merged = merge_frontmatter(existing, row)
    fm_block = render_frontmatter(merged)

    byline = f"> _Mirror regenerated: Claude Code · {model_name} · {date_str} (D-156)_"
    body_stripped = body.lstrip("\n")
    byline_added = False
    if byline not in body_stripped[:2000]:
        # Insert under the first H1 title line if present, else at top of body.
        lines = body_stripped.split("\n")
        insert_at = 0
        for i, ln in enumerate(lines):
            if ln.startswith("# "):
                insert_at = i + 1
                break
        # skip existing blank/byline-ish lines right after title to insert cleanly
        lines.insert(insert_at, ("" if insert_at == 0 else "") )
        lines[insert_at] = byline if insert_at == 0 else lines[insert_at]
        if insert_at != 0:
            lines.insert(insert_at, byline)
        else:
            lines[insert_at] = byline
        body_new = "\n".join(lines)
        byline_added = True
    else:
        body_new = body_stripped

    return fm_block + "\n" + body_new, existing is not None, byline_added


# ---------------------------------------------------------------------------
# INDEX.md generation
# ---------------------------------------------------------------------------


def generate_index(rows: list[MapRow]) -> str:
    date_str = datetime.date.today().isoformat()
    lines = []
    lines.append("# Documentation Index — Generated View (D-156)")
    lines.append("")
    lines.append(f"> _Mirror regenerated: Claude Code · {MODEL_BYLINE} · {date_str} (D-156)_")
    lines.append(">")
    lines.append(
        "> Generated by `scripts/docstore/mirror_docs.py` from the docstore mapping CSV. "
        "Do not hand-edit — the next `--apply` run overwrites this file. Grouped by type, "
        "then domain, with status and supersession shown per row."
    )
    lines.append("")

    by_type: dict[str, list[MapRow]] = {}
    for r in rows:
        by_type.setdefault(r.doc_type, []).append(r)

    for t in RULED_TYPES:
        trows = by_type.get(t, [])
        if not trows:
            continue
        lines.append(f"## {t} ({len(trows)})")
        lines.append("")
        by_domain: dict[str, list[MapRow]] = {}
        for r in trows:
            key = ",".join(sorted(r.domains)) or "(none)"
            by_domain.setdefault(key, []).append(r)
        for domain_key in sorted(by_domain.keys()):
            drows = sorted(by_domain[domain_key], key=lambda r: r.title.lower())
            lines.append(f"### domain: {domain_key} ({len(drows)})")
            lines.append("")
            lines.append("| Title | Status | Path | Supersedes |")
            lines.append("|---|---|---|---|")
            for r in drows:
                sup = f"[{r.supersedes_path}]({_index_link(r.supersedes_path)})" if r.supersedes_path else ""
                lines.append(
                    f"| {r.title} | {r.status} | [{r.mirror_path}]({_index_link(r.mirror_path)}) | {sup} |"
                )
            lines.append("")

    return "\n".join(lines) + "\n"


def _index_link(mirror_path: str) -> str:
    # INDEX.md lives at docs/INDEX.md; mirror_path is "docs/<type>/<file>"
    if mirror_path.startswith("docs/"):
        return mirror_path[len("docs/"):]
    return mirror_path


# ---------------------------------------------------------------------------
# --plan
# ---------------------------------------------------------------------------


def cmd_plan(args) -> int:
    csv_path = Path(args.mapping_csv)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    rows = load_mapping(csv_path)
    verification = verify_mapping(rows)

    fatal = bool(verification["missing_sources"]) or bool(verification["duplicate_mirror_paths"])

    move_rows = [r for r in rows if r.moves]
    noop_rows = [r for r in rows if not r.moves]

    per_type: dict[str, int] = {}
    per_status: dict[str, int] = {}
    for r in rows:
        per_type[r.doc_type] = per_type.get(r.doc_type, 0) + 1
        per_status[r.status] = per_status.get(r.status, 0) + 1

    print(f"[plan] mapping CSV: {csv_path} ({len(rows)} rows)")
    print(f"[plan] missing sources: {len(verification['missing_sources'])}")
    print(f"[plan] duplicate mirror_paths: {len(verification['duplicate_mirror_paths'])}")
    print(f"[plan] bad doc_type values: {len(verification['bad_types'])}")
    print(f"[plan] bad status values: {len(verification['bad_status'])}")
    print(f"[plan] moves: {len(move_rows)}  no-op (already at target): {len(noop_rows)}")

    if fatal:
        print("[plan] FATAL verification failures — plan will still be computed for reporting, "
              "but must not be applied until resolved.", file=sys.stderr)

    print("[plan] computing dead-links-before (live tree, walk-G method) ...")
    before_scanned, before_checked, before_dead = compute_dead_links_before()
    print(f"[plan]   scanned {before_scanned} .md files, {before_checked} links checked, "
          f"{len(before_dead)} dead")

    print("[plan] computing link rewrites + projected dead-links-after ...")
    rewrites, after_scanned, after_checked, after_dead = compute_link_rewrites_and_projected_dead(rows)
    print(f"[plan]   scanned {after_scanned} .md files, {after_checked} links checked, "
          f"{len(rewrites)} rewrites, {len(after_dead)} projected dead")

    delta = len(after_dead) - len(before_dead)
    verdict = "OK (did not rise)" if delta <= 0 else "WOULD RISE — DO NOT APPLY AS-IS"
    print(f"[plan] dead-link delta: {delta:+d}  -> {verdict}")

    plan = {
        "generated_at": datetime.datetime.now().isoformat(timespec="seconds"),
        "mapping_csv": str(csv_path),
        "repo_root": str(REPO_ROOT),
        "counts": {
            "total_rows": len(rows),
            "moves": len(move_rows),
            "no_ops": len(noop_rows),
            "per_type": per_type,
            "per_status": per_status,
        },
        "verification": {
            "missing_sources": verification["missing_sources"],
            "duplicate_mirror_paths": verification["duplicate_mirror_paths"],
            "bad_doc_types": verification["bad_types"],
            "bad_status": verification["bad_status"],
            "fatal": fatal,
        },
        "move_list": [{"source_path": r.source_path, "mirror_path": r.mirror_path} for r in move_rows],
        "link_rewrites": [
            {
                "file_old": rw.file_old, "file_new": rw.file_new,
                "target_old": rw.target_old, "target_new": rw.target_new,
                "resolved_target_old": rw.resolved_target_old,
                "resolved_target_new": rw.resolved_target_new,
            }
            for rw in rewrites
        ],
        "dead_links": {
            "before": {
                "scanned_files": before_scanned, "checked_links": before_checked,
                "count": len(before_dead),
                "items": [{"file": d.file, "target": d.target, "reason": d.reason} for d in before_dead],
            },
            "after_projected": {
                "scanned_files": after_scanned, "checked_links": after_checked,
                "count": len(after_dead),
                "items": [{"file": d.file, "target": d.target, "reason": d.reason} for d in after_dead],
            },
            "delta": delta,
            "verdict": verdict,
        },
        "long_paths_used": sorted(_LONGPATH_USED),
    }

    plan_json = out_dir / "mirror-plan.json"
    with open(plan_json, "w", encoding="utf-8") as f:
        json.dump(plan, f, indent=2, ensure_ascii=False)
    print(f"[plan] wrote {plan_json}")

    plan_md = out_dir / "mirror-plan.md"
    with open(plan_md, "w", encoding="utf-8") as f:
        f.write(render_plan_md(plan))
    print(f"[plan] wrote {plan_md}")

    return 1 if fatal else 0


def render_plan_md(plan: dict) -> str:
    date_str = datetime.date.today().isoformat()
    lines = []
    lines.append("# mirror_docs.py --plan summary (D-156)")
    lines.append("")
    lines.append(f"> _Byline: Claude Code · {MODEL_BYLINE} · {date_str}_")
    lines.append("")
    lines.append(f"Mapping CSV: `{plan['mapping_csv']}`  ")
    lines.append(f"Generated: {plan['generated_at']}")
    lines.append("")
    c = plan["counts"]
    lines.append("## Counts")
    lines.append("")
    lines.append(f"- Total mapped rows: **{c['total_rows']}**")
    lines.append(f"- Moves: **{c['moves']}**   No-op (already at target path): **{c['no_ops']}**")
    lines.append("")
    lines.append("### Files per folder (doc_type)")
    lines.append("")
    lines.append("| doc_type | count |\n|---|---|")
    for t in RULED_TYPES:
        lines.append(f"| {t} | {c['per_type'].get(t, 0)} |")
    lines.append("")
    lines.append("### Rows per status")
    lines.append("")
    lines.append("| status | count |\n|---|---|")
    for s in RULED_STATUS:
        lines.append(f"| {s} | {c['per_status'].get(s, 0)} |")
    lines.append("")

    v = plan["verification"]
    lines.append("## Verification")
    lines.append("")
    lines.append(f"- Missing sources: **{len(v['missing_sources'])}**")
    for p in v["missing_sources"][:20]:
        lines.append(f"  - {p}")
    lines.append(f"- Duplicate mirror_paths: **{len(v['duplicate_mirror_paths'])}**")
    for m, srcs in list(v["duplicate_mirror_paths"].items())[:20]:
        lines.append(f"  - {m}: {srcs}")
    lines.append(f"- Bad doc_type values: **{len(v['bad_doc_types'])}**")
    lines.append(f"- Bad status values: **{len(v['bad_status'])}**")
    lines.append(f"- **FATAL: {v['fatal']}**")
    lines.append("")

    dl = plan["dead_links"]
    lines.append("## Dead links (walk-G method: docs/**/*.md excl. docs/private/, "
                  "relative targets, existence test)")
    lines.append("")
    lines.append(f"- Before: scanned {dl['before']['scanned_files']} files, "
                  f"{dl['before']['checked_links']} links checked, "
                  f"**{dl['before']['count']} dead**")
    lines.append(f"- Projected after: scanned {dl['after_projected']['scanned_files']} files, "
                  f"{dl['after_projected']['checked_links']} links checked, "
                  f"**{dl['after_projected']['count']} dead**")
    lines.append(f"- Delta: **{dl['delta']:+d}**  -> **{dl['verdict']}**")
    lines.append(f"- Link rewrites computed: **{len(plan['link_rewrites'])}**")
    lines.append("")

    if plan["long_paths_used"]:
        lines.append(f"## Long paths (>= 240 chars) requiring `\\\\?\\` prefix: "
                      f"{len(plan['long_paths_used'])}")
        for p in plan["long_paths_used"][:10]:
            lines.append(f"  - {p}")
        lines.append("")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# --index-only
# ---------------------------------------------------------------------------


def cmd_index_only(args) -> int:
    csv_path = Path(args.mapping_csv)
    rows = load_mapping(csv_path)
    content = generate_index(rows)
    preview_path = Path(args.scratch_dir) / "INDEX-preview.md"
    preview_path.parent.mkdir(parents=True, exist_ok=True)
    with open(preview_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"[index-only] {len(rows)} rows -> preview written to {preview_path} "
          f"(NOT written to the repo)")
    return 0


# ---------------------------------------------------------------------------
# --apply (built, verified never invoked by the build/dry-run job)
# ---------------------------------------------------------------------------


def git_mv(src: Path, dst: Path) -> None:
    """Move a managed doc, preferring `git mv` so history follows the file.

    Falls back to a plain filesystem move when git refuses. WHY: some managed
    docs are deliberately untracked -- docs/INFRASTRUCTURE.md is gitignored by
    name (.gitignore:95) because it carries credential-shaped lines, and its
    tracked counterpart is INFRASTRUCTURE.template.md. `git mv` on such a file
    exits non-zero, and with check=True that aborted the whole run partway
    through, leaving a half-migrated tree with no rollback. Force-adding it
    instead would put secrets into tracked history, which is the one hard line.
    The fallback relocates the file so links still resolve, and leaves its git
    status exactly as it was.
    """
    dst.parent.mkdir(parents=True, exist_ok=True)
    result = subprocess.run(
        ["git", "mv", "--", str(src), str(dst)],
        cwd=str(REPO_ROOT), capture_output=True, text=True,
    )
    if result.returncode == 0:
        return
    # NEVER overwrite. On Windows the filesystem is case-INSENSITIVE, so a
    # destination can collide with a DIFFERENT row's not-yet-moved source:
    # row 22 moves docs/INDEX.md -> docs/blueprint/INDEX.md while row 197's
    # source is docs/blueprint/index.md -- the same path here. `git mv`
    # refuses that, correctly. A blind shutil.move does not: on 2026-09-09 it
    # clobbered blueprint/index.md ("# Platform Blueprint") with INDEX.md's
    # text, and the next row carried the wrong content onward. Aborting keeps
    # the tree recoverable, which is the whole point of refusing.
    if dst.exists():
        raise RuntimeError(
            f"refusing to move {src} -> {dst}: destination already exists "
            f"(case-insensitive collision with another row's source?). "
            f"git mv said: {result.stderr.strip()}"
        )
    shutil.move(str(src), str(dst))
    print(f"[apply] untracked/ignored, moved without git: {src.relative_to(REPO_ROOT)}")


def cmd_apply(args) -> int:
    csv_path = Path(args.mapping_csv)
    out_dir = Path(args.out_dir)
    rows = load_mapping(csv_path)
    verification = verify_mapping(rows)
    if verification["missing_sources"] or verification["duplicate_mirror_paths"]:
        print("[apply] REFUSING: verification failed (missing sources or duplicate mirror "
              "paths). Re-run --plan and fix the mapping CSV first.", file=sys.stderr)
        return 2

    before_scanned, before_checked, before_dead = compute_dead_links_before()
    before_count = len(before_dead)

    rewrites, _, _, _ = compute_link_rewrites_and_projected_dead(rows)
    rewrite_index: dict[str, list[LinkRewrite]] = {}
    for rw in rewrites:
        rewrite_index.setdefault(rw.file_old, []).append(rw)

    date_str = datetime.date.today().isoformat()
    model_name = args.model or MODEL_BYLINE

    # 1) git mv every moving file
    for r in rows:
        if not r.moves:
            continue
        src = REPO_ROOT / r.source_path
        dst = REPO_ROOT / r.mirror_path
        git_mv(src, dst)

    # 2) rewrite links + inject frontmatter in every managed file at its NEW location
    for r in rows:
        dst = REPO_ROOT / r.mirror_path
        text = read_text(dst)
        for rw in rewrite_index.get(r.source_path, []):
            if rw.target_old in text:
                text = text.replace(f"]({rw.target_old})", f"]({rw.target_new})")
        text, _had_fm, _byline_added = apply_frontmatter_and_byline(text, r, model_name, date_str)
        with open(winlong(dst), "w", encoding="utf-8", newline="\n") as f:
            f.write(text)

    # 3) regenerate INDEX.md
    index_content = generate_index(rows)
    with open(winlong(REPO_ROOT / "docs" / "INDEX.md"), "w", encoding="utf-8", newline="\n") as f:
        f.write(index_content)

    # 4) re-check dead links; refuse (report only, no rollback) if it rose
    after_scanned, after_checked, after_dead = compute_dead_links_before()
    after_count = len(after_dead)

    report = {
        "before_count": before_count,
        "after_count": after_count,
        "delta": after_count - before_count,
    }
    report_path = out_dir / "apply-deadlink-check.json"
    with open(report_path, "w", encoding="utf-8") as f:
        json.dump({
            **report,
            "after_items": [{"file": d.file, "target": d.target, "reason": d.reason} for d in after_dead],
        }, f, indent=2)

    if after_count > before_count:
        print(f"[apply] DEAD LINK COUNT ROSE: {before_count} -> {after_count} "
              f"(+{after_count - before_count}). Files were already moved and modified. "
              f"NOT rolling back automatically — revert via git (git status / git diff / "
              f"git checkout / git mv back as needed). Offending links written to "
              f"{report_path}.", file=sys.stderr)
        for d in after_dead[:40]:
            print(f"    {d.file} -> {d.target}  ({d.reason})", file=sys.stderr)
        return 3

    print(f"[apply] dead-link count: {before_count} -> {after_count} (did not rise). "
          f"Moved {sum(1 for r in rows if r.moves)} files, regenerated docs/INDEX.md.")
    return 0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def build_argparser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[1] if __doc__ else "")
    mode = p.add_mutually_exclusive_group()
    mode.add_argument("--plan", action="store_true", help="Compute and write the plan (default).")
    mode.add_argument("--apply", action="store_true", help="Execute the plan (git mv, frontmatter, INDEX.md).")
    mode.add_argument("--index-only", action="store_true", help="Regenerate INDEX.md preview only, to scratch.")
    p.add_argument("--mapping-csv", default=str(DEFAULT_MAPPING_CSV))
    p.add_argument("--out-dir", default=str(DEFAULT_OUT_DIR))
    p.add_argument("--scratch-dir", default=str(DEFAULT_SCRATCH_DIR))
    p.add_argument("--model", default=None, help="Model name for the mirror-regenerated byline (apply only).")
    return p


def main(argv: Optional[list[str]] = None) -> int:
    args = build_argparser().parse_args(argv)
    if args.apply:
        return cmd_apply(args)
    if args.index_only:
        return cmd_index_only(args)
    return cmd_plan(args)


if __name__ == "__main__":
    raise SystemExit(main())
