// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {time} from '../models';

export function Browse():Promise<string>;

export function BrowseForExport(arg1:string):Promise<string>;

export function DetectCloudDrives():Promise<void>;

export function ExportResults(arg1:string,arg2:string):Promise<void>;

export function ExportSettings(arg1:string):Promise<void>;

export function GetCloudDrives():Promise<Array<main.CloudDrive>>;

export function GetCurrentProgress():Promise<main.ScanProgress>;

export function GetCurrentTime():Promise<time.Time>;

export function GetLogs():Promise<Array<string>>;

export function GetScanStatus():Promise<main.ScanStatus>;

export function GetSettings():Promise<main.Settings>;

export function ImportSettings(arg1:string):Promise<void>;

export function LoadChildrenLazy(arg1:string,arg2:number):Promise<Array<main.FileNode>>;

export function PauseScan():Promise<void>;

export function ResumeScan():Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function StartScan(arg1:main.ScanOptions):Promise<main.FileNode>;

export function StopScan():Promise<void>;

export function SubscribeScanProgress():Promise<void>;
