"""Capture the live schema as the reproducible bootstrap baseline (Codex C-02).

Byline: Claude Code . Fable 5 . 2026-08-02

WHY: the numbered migration chain is historical, not self-contained — custody
tables (evidence.source/file_node/custody_event), the raw_* family, all of
analysis/reference/ops, and the ai schema's types were applied out-of-band, so
0012/0015 reference objects the chain never creates and a fresh
`psql -f 0001..0016` fails mid-way. An opposing expert (and CI) must be able to
reproduce the schema from the repo alone (hashing audit finding 1; Codex C-02).

CONTRACT (recorded in sql/README.md):
  * sql/NNNN_*.sql        — the historical, append-only chain. Never edited
                             after apply; future changes keep landing here.
  * sql/bootstrap/schema_baseline.sql — a pg_dump --schema-only snapshot of
                             the ENTIRE live database, regenerated by this
                             script after any applied migration. Bootstrapping
                             an empty database = apply THIS ONE FILE.

usage:  uv run python scripts/capture_bootstrap_ddl.py --host <ip> [--verify]
        --verify restores the capture into a scratch database on the same
        server and compares per-schema table counts against live, then drops
        the scratch DB (structure-only; no data ever moves).
"""

from __future__ import annotations

import argparse
import datetime
import os
import pathlib
import re
import subprocess

from sqlalchemy import create_engine, text

REPO = pathlib.Path(__file__).resolve().parents[1]
PGBIN = pathlib.Path(r"C:\Program Files\PostgreSQL\18\bin")
OUT = REPO / "sql" / "bootstrap" / "schema_baseline.sql"
SCRATCH = "ai_bootstrap_check"
SCHEMAS = ("ai", "evidence", "working", "analysis", "reference", "ops", "public")


def settings(host: str) -> dict[str, str]:
    env: dict[str, str] = {}
    dotenv = REPO / ".env"
    if dotenv.exists():
        for line in dotenv.read_text(encoding="utf-8", errors="ignore").splitlines():
            m = re.match(r"^\s*([A-Z_]+)\s*=\s*(.+?)\s*$", line)
            if m:
                env[m.group(1)] = m.group(2).strip("\"'")
    for k in ("DB_USER", "DB_PASS", "DB_DATABASE"):
        if k in os.environ:
            env[k] = os.environ[k]
    env["DB_HOST"] = host
    env.setdefault("DB_PORT", "5432")
    return env


def run(cmd: list[str], env: dict[str, str], stdin=None, stdout=None) -> None:
    child = dict(os.environ)
    child["PGPASSWORD"] = env["DB_PASS"]
    proc = subprocess.run(cmd, env=child, stdin=stdin, stdout=stdout,
                          stderr=subprocess.PIPE, text=True)
    if proc.returncode != 0:
        raise SystemExit(f"{pathlib.Path(cmd[0]).stem} failed:\n{proc.stderr[-1500:]}")


def table_counts(engine) -> dict[str, int]:
    with engine.connect() as c:
        rows = c.execute(text(
            "SELECT table_schema, count(*) FROM information_schema.tables "
            "WHERE table_schema = ANY(:s) AND table_type = 'BASE TABLE' "
            "GROUP BY 1"), {"s": list(SCHEMAS)}).all()
    return dict(rows)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--host", required=True)
    ap.add_argument("--verify", action="store_true")
    args = ap.parse_args()
    env = settings(args.host)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    stamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    header = (
        "-- sql/bootstrap/schema_baseline.sql — REPRODUCIBLE BOOTSTRAP (Codex C-02).\n"
        f"-- Captured {stamp} from the live database by scripts/capture_bootstrap_ddl.py.\n"
        "-- Apply to an EMPTY database to reproduce the full live schema. The numbered\n"
        "-- sql/NNNN chain remains the historical record; regenerate this file after\n"
        "-- applying any new numbered migration. Structure only — never data.\n\n"
    )
    with OUT.open("w", encoding="utf-8") as fh:
        fh.write(header)
        fh.flush()
        run([str(PGBIN / "pg_dump.exe"), "--schema-only", "--no-owner",
             "--no-privileges", "-h", env["DB_HOST"], "-p", env["DB_PORT"],
             "-U", env["DB_USER"], "-d", env["DB_DATABASE"]], env, stdout=fh)
    print(f"baseline: {OUT.stat().st_size / 1024:,.0f} KiB -> {OUT}")

    if not args.verify:
        return

    url = (f"postgresql+psycopg://{env['DB_USER']}:{env['DB_PASS']}"
           f"@{env['DB_HOST']}:{env['DB_PORT']}")
    admin = create_engine(url + "/postgres", isolation_level="AUTOCOMMIT",
                          connect_args={"connect_timeout": 60})
    with admin.connect() as c:
        c.execute(text(f'DROP DATABASE IF EXISTS "{SCRATCH}" WITH (FORCE)'))
        c.execute(text(f'CREATE DATABASE "{SCRATCH}"'))
    with OUT.open("r", encoding="utf-8") as fh:
        run([str(PGBIN / "psql.exe"), "-q", "-v", "ON_ERROR_STOP=0",
             "-h", env["DB_HOST"], "-p", env["DB_PORT"], "-U", env["DB_USER"],
             "-d", SCRATCH], env, stdin=fh, stdout=subprocess.DEVNULL)

    live = table_counts(create_engine(url + f"/{env['DB_DATABASE']}",
                                      connect_args={"connect_timeout": 60}))
    scratch = table_counts(create_engine(url + f"/{SCRATCH}",
                                         connect_args={"connect_timeout": 60}))
    ok = True
    for sch in sorted(set(live) | set(scratch)):
        a, b = live.get(sch, 0), scratch.get(sch, 0)
        flag = "OK " if a == b else "MISMATCH"
        if a != b:
            ok = False
        print(f"  {flag} {sch:10s} live={a:3d} bootstrap={b:3d}")
    with admin.connect() as c:
        c.execute(text(f'DROP DATABASE IF EXISTS "{SCRATCH}" WITH (FORCE)'))
    print("verify:", "PASS — clean bootstrap reproduces the live schema" if ok else "FAIL")
    raise SystemExit(0 if ok else 1)


if __name__ == "__main__":
    main()
