// Byline: Codex · GPT-6.1 · 2026-10-06. Selective port from held 7a1db624; independent byte-only operation.
package sourceintegrity_test

import (
	"context"
	"errors"
	"io"
	"strings"
	"testing"

	"github.com/Cursedpotential/probata/engine/sourceintegrity"
)

// syntheticReader generates a bounded stream without retaining its complete contents.
// Inputs: byte length, optional nonzero offset and terminal error. Outputs: generated reads and call counts.
// Side effects: advances synthetic counters; pick for whole-stream and late-error coverage tests.
type syntheticReader struct {
	size, offset, nonzero int64
	terminal              error
	calls, maxBuffer      int
}

// Read generates zero bytes with one optional nonzero byte and a chosen terminal error.
// Input: destination buffer. Output: generated bytes and error. Side effects: synthetic counters only.
// Pick to prove fixed-buffer coverage without allocating a corpus or touching local source copies.
func (r *syntheticReader) Read(p []byte) (int, error) {
	r.calls++
	if len(p) > r.maxBuffer {
		r.maxBuffer = len(p)
	}
	if r.offset == r.size {
		if r.terminal != nil {
			return 0, r.terminal
		}
		return 0, io.EOF
	}
	n := len(p)
	if remaining := r.size - r.offset; int64(n) > remaining {
		n = int(remaining)
	}
	clear(p[:n])
	if r.nonzero >= r.offset && r.nonzero < r.offset+int64(n) {
		p[r.nonzero-r.offset] = 1
	}
	r.offset += int64(n)
	return n, nil
}

// TestInspectStreamWholeCoverage proves empty/all-zero outcomes require EOF and matching size.
// Inputs: synthetic streams covering multiple fixed buffers. Outputs: exact coverage and unassessed-format assertions.
// Side effects: no filesystem I/O; pick for zero-content contract regressions.
func TestInspectStreamWholeCoverage(t *testing.T) {
	for _, size := range []int64{0, 1, 65536, (3 << 20) + 17} {
		reader := &syntheticReader{size: size, nonzero: -1}
		result, err := sourceintegrity.InspectStream(context.Background(), reader, size)
		want := "all_zero"
		if size == 0 {
			want = "zero_byte"
		}
		if err != nil || result.Status != want || !result.Complete || !result.EOFReached || result.CheckedBytes != size || result.NonzeroObserved {
			t.Fatalf("size %d: %+v, %v", size, result, err)
		}
		if result.CheckVersion != sourceintegrity.CheckVersion || result.FormatValidation != "unassessed" || reader.maxBuffer > 64<<10 {
			t.Fatalf("coverage or memory contract failed: %+v, maxBuffer=%d", result, reader.maxBuffer)
		}
	}
}

// TestInspectStreamLateNonzeroNeverClaimsGood disproves whole-file zero conclusions from an all-zero prefix.
// Input: a nonzero byte after three 64 KiB buffers. Output: complete nonzero observation and unknown usability.
// Side effects: synthetic stream reads only; pick for range-sampling false-positive protection.
func TestInspectStreamLateNonzeroNeverClaimsGood(t *testing.T) {
	reader := &syntheticReader{size: (4 << 16) + 7, nonzero: (3 << 16) + 2}
	result, err := sourceintegrity.InspectStream(context.Background(), reader, reader.size)
	if err != nil || !result.Complete || !result.NonzeroObserved || result.Status != "unknown" || result.CheckedBytes != reader.size || result.Reason != "format_validation_unassessed" {
		t.Fatalf("late nonzero evidence wrong: %+v, %v", result, err)
	}
}

// TestInspectStreamFailureCoverage preserves unknown status when a read or expected-size check fails.
// Inputs: I/O errors and both short/long streams. Outputs: incomplete assessments with exact checked-byte counts.
// Side effects: synthetic stream reads only; pick for failed coverage, never verified-good inference.
func TestInspectStreamFailureCoverage(t *testing.T) {
	readFailure := errors.New("synthetic access failed")
	for _, test := range []struct {
		name     string
		size     int64
		expected int64
		terminal error
		reason   string
		eof      bool
	}{
		{"read-failure", 8193, 8193, readFailure, "stream_read_failed", false},
		{"unexpected-eof", 8193, 8193, io.ErrUnexpectedEOF, "stream_read_failed", false},
		{"short", 17, 18, nil, "source_size_mismatch", true},
		{"long", 18, 17, nil, "source_size_mismatch", true},
		{"missing", 0, 17, nil, "source_size_mismatch", true},
	} {
		t.Run(test.name, func(t *testing.T) {
			reader := &syntheticReader{size: test.size, nonzero: -1, terminal: test.terminal}
			result, err := sourceintegrity.InspectStream(context.Background(), reader, test.expected)
			if err == nil || result.Status != "unknown" || result.Complete || result.EOFReached != test.eof || result.CheckedBytes != test.size || result.Reason != test.reason {
				t.Fatalf("failed coverage wrong: %+v, %v", result, err)
			}
		})
	}
}

// readerFunc adapts a synthetic read callback for cancellation and no-progress edge cases.
// Input: read callback. Output: io.Reader implementation. Side effects: callback-defined synthetic reads only.
type readerFunc func([]byte) (int, error)

// Read invokes the synthetic callback.
// Input: read buffer. Output: callback bytes/error. Side effects: callback counters only.
func (f readerFunc) Read(p []byte) (int, error) { return f(p) }

// TestInspectStreamCancellationDoesNotBecomeZero requires unknown coverage before and during cancellation.
// Inputs: pre-canceled context and cancellation returned with final bytes/EOF. Outputs: preserved byte count and incomplete status.
// Side effects: synthetic context cancellation only; pick for cancellation priority over apparent successful EOF.
func TestInspectStreamCancellationDoesNotBecomeZero(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	reader := &syntheticReader{size: 1, nonzero: -1}
	result, err := sourceintegrity.InspectStream(ctx, reader, 1)
	if !errors.Is(err, context.Canceled) || reader.calls != 0 || result.Complete || result.Status != "unknown" {
		t.Fatalf("pre-cancel wrong: %+v, %v", result, err)
	}
	ctx, cancel = context.WithCancel(context.Background())
	defer cancel()
	result, err = sourceintegrity.InspectStream(ctx, readerFunc(func(p []byte) (int, error) {
		p[0] = 0
		cancel()
		return 1, io.EOF
	}), 1)
	if !errors.Is(err, context.Canceled) || result.Complete || result.EOFReached || result.CheckedBytes != 1 || result.Status != "unknown" {
		t.Fatalf("mid-read cancel wrong: %+v, %v", result, err)
	}
}

// TestInspectStreamReaderEdgeCases covers EOF-with-data, short successful reads and bounded no-progress retries.
// Inputs: synthetic readers exercising legal reader shapes. Outputs: completion and bounded failure assertions.
// Side effects: synthetic counters only; pick for reader-contract regressions.
func TestInspectStreamReaderEdgeCases(t *testing.T) {
	result, err := sourceintegrity.InspectStream(context.Background(), readerFunc(func(p []byte) (int, error) {
		p[0] = 0
		return 1, io.EOF
	}), -1)
	if err != nil || result.Status != "all_zero" || result.CheckedBytes != 1 || !result.Complete {
		t.Fatalf("data and EOF wrong: %+v, %v", result, err)
	}
	reads := 0
	result, err = sourceintegrity.InspectStream(context.Background(), readerFunc(func(p []byte) (int, error) {
		reads++
		if reads < 4 {
			p[0] = 0
			return 1, nil
		}
		return 0, io.EOF
	}), 3)
	if err != nil || !result.Complete || result.Status != "all_zero" || result.CheckedBytes != 3 {
		t.Fatalf("short successful reads wrong: %+v, %v", result, err)
	}
	reads = 0
	result, err = sourceintegrity.InspectStream(context.Background(), readerFunc(func([]byte) (int, error) {
		reads++
		return 0, nil
	}), -1)
	if !errors.Is(err, io.ErrNoProgress) || reads != 100 || result.Complete || result.Status != "unknown" {
		t.Fatalf("no-progress bound wrong: %+v, %v, reads=%d", result, err, reads)
	}
}

// TestInspectStreamInvalidInputAndUnknownSize keeps invalid requests unknown and supports unspecified size.
// Inputs: invalid reader/context/size combinations and a text stream with unknown expected length.
// Outputs: fixed reasons and nonzero/unknown usability; side effects: synthetic reads only.
func TestInspectStreamInvalidInputAndUnknownSize(t *testing.T) {
	for _, test := range []struct {
		ctx    context.Context
		reader io.Reader
		size   int64
	}{{nil, strings.NewReader("x"), -1}, {context.Background(), nil, -1}, {context.Background(), strings.NewReader("x"), -2}} {
		result, err := sourceintegrity.InspectStream(test.ctx, test.reader, test.size)
		if err == nil || result.Status != "unknown" || result.Complete || result.CheckedBytes != 0 || result.Reason != "invalid_stream_input" {
			t.Fatalf("invalid input wrong: %+v, %v", result, err)
		}
	}
	result, err := sourceintegrity.InspectStream(context.Background(), strings.NewReader("positive size is not proof"), -1)
	if err != nil || !result.NonzeroObserved || !result.Complete || result.Status != "unknown" {
		t.Fatalf("unknown expected size wrong: %+v, %v", result, err)
	}
}
