"""Structural check that the Phase 0 tree actually exists on disk.

> _Byline: Grok · grok-4.6 · 2026-08-18_
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

REQUIRED = [
    "AGENTS.md",
    "README.md",
    "pyproject.toml",
    "compose.yaml",
    "sql/0001_legal_os_bootstrap.sql",
    "api/legal_workspace/api/main.py",
    "api/legal_workspace/services/source_package.py",
    "web/package.json",
    "web/src/app/page.tsx",
    "web/src/app/custody-factors/page.tsx",
    "web/src/app/drafts/page.tsx",
    "api/legal_workspace/services/workspace.py",
    "api/legal_workspace/services/persist.py",
    "api/legal_workspace/domain/strategy.py",
    "api/legal_workspace/domain/authority_library.py",
    "web/src/app/private-notes/page.tsx",
    "web/src/app/challenge-draft/page.tsx",
    "web/src/app/tasks/page.tsx",
    "api/legal_workspace/domain/redteam.py",
    "api/legal_workspace/domain/todos.py",
    "api/legal_workspace/domain/review.py",
    "api/legal_workspace/domain/release.py",
    "web/src/app/review/page.tsx",
    "web/src/app/final-copy/page.tsx",
    "web/src/app/open-questions/page.tsx",
    "api/legal_workspace/domain/research.py",
    "api/legal_workspace/domain/templates.py",
    "web/src/app/templates/page.tsx",
    "web/src/app/evidence-requests/page.tsx",
    "web/src/app/missing-evidence/page.tsx",
    "api/legal_workspace/domain/discovery.py",
    "api/legal_workspace/domain/investigation.py",
    "api/legal_workspace/domain/exhibits.py",
    "web/src/app/evidence/page.tsx",
    "tests/test_exhibits.py",
    "api/legal_workspace/domain/privilege.py",
    "api/legal_workspace/domain/provider_grid.py",
    "api/legal_workspace/api/privilege_routes.py",
    "web/src/app/confidentiality-check/page.tsx",
    "tests/test_privilege.py",
    "tests/test_provider_grid.py",
    "api/legal_workspace/services/automation/scheduler.py",
    "api/legal_workspace/services/automation/bus.py",
    "api/legal_workspace/services/automation/runner.py",
    "api/legal_workspace/api/automation_routes.py",
    "sql/0002_legal_automations.sql",
    "tests/test_automation.py",
    "api/legal_workspace/domain/calendar.py",
    "web/src/app/calendar/page.tsx",
    "web/src/app/timeline/page.tsx",
    "web/src/app/filing-checklist/page.tsx",
    "api/legal_workspace/domain/filing.py",
    "api/legal_workspace/domain/agents.py",
    "api/legal_workspace/services/routing.py",
    "api/legal_workspace/api/routing_routes.py",
    "config/routing.json",
    "web/src/app/assistant-log/page.tsx",
    "web/src/components/RoutingEditor.tsx",
    "api/legal_workspace/domain/support_map.py",
    "api/legal_workspace/services/gateway.py",
    "api/legal_workspace/services/agno_client.py",
    "tests/test_agno_client.py",
    "tests/test_matter_projection.py",
    "api/legal_workspace/services/docx_export.py",
    "api/legal_workspace/services/redaction.py",
    "api/legal_workspace/services/bates.py",
    "tests/test_redaction.py",
    "tests/test_bates.py",
    "tests/test_confidential.py",
    "data/workspace/.gitkeep",
    "scripts/run_local.ps1",
    "scripts/seed_mock_workspace.py",
    "docs/LEGAL-WORKSPACE-BUILD-GUIDE-2026-08-17.md",
    "docs/DEPLOYMENT_PLAN.md",
    "docs/planning/HANDOFF-ANALYSIS.md",
    "docs/planning/DONOR-ANALYSIS.md",
]


def test_required_scaffold_files_exist() -> None:
    missing = [rel for rel in REQUIRED if not (ROOT / rel).exists()]
    assert missing == [], f"missing scaffold files: {missing}"
